### ISSUE TITLE
License is missing...

### ISSUE THREAD

**Issue by Areso** [dkirkby/conjugo#3]
Hey!
I am learning Spanish language (from English, though it is not my native language), so, I use alot of apps, dictionaries and so on.
I even wrote my own https://github.com/Areso/Spanish-exercises , which currently is work-in-progress.
TIL that there is a somewhat similar (but much more advanced) project, yours, though it is written with Jupyter, which I am trying to learn too for my gamedev pet-projects.
I already forked and cloned your project, but I would like to know, on which conditions I could use it?
For that purpose I kindly asking you to add some License to your project, so, people could not only learn from it, but re-use it partly or whole. 
Thanks in advance,
Anton.

**Comment by dkirkby** [comment]
Thanks for the suggestion.  I just added an MIT license.
